from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PATHS = [
    "docs/Kuroii_Motion_AI_Suite_Documentation_v3.0/00_README_Document_Index.md",
    "视觉UI参考",
    "apps/desktop/src/app-shell.js",
    "apps/local-service/src/service-shell.js",
    "apps/local-service/src/server.py",
    "apps/local-service/src/config.py",
    "apps/local-service/src/data_store.py",
    "apps/local-service/src/envelopes.py",
    "apps/local-service/src/redaction.py",
    "extensions/after-effects/CSXS/manifest.xml",
    "extensions/after-effects/host/index.jsx",
    "extensions/premiere-pro/CSXS/manifest.xml",
    "extensions/premiere-pro/host/index.jsx",
    "packages/ui-system/tokens/design-tokens.json",
    "packages/i18n/src/locales/zh-CN.json",
    "packages/i18n/src/locales/en-US.json",
    "packages/provider-hub/src/provider-errors.js",
    "packages/provider-hub/manifests/openai-compatible.json",
    "packages/provider-hub/manifests/openai.json",
    "packages/provider-hub/manifests/deepseek.json",
    "packages/provider-hub/manifests/custom-base-url.json",
    "packages/provider-hub/manifests/minimax.json",
    "packages/command-bus/schemas/command-envelope.schema.json",
    "packages/command-bus/schemas/result-envelope.schema.json",
    "packages/action-schema/schemas/action.schema.json",
    "packages/capability-registry/registry/ae.capabilities.json",
    "packages/capability-registry/registry/pr.capabilities.json",
    "packages/host-adapters/src/ae-adapter.js",
    "packages/host-adapters/src/pr-adapter.js",
    "packages/security/permissions.json",
    "packages/workflow/schemas/workflow.schema.json",
    "tests/smoke_local_service.py",
    "docs/LOCAL_SERVICE_FIRST_SLICE_v0.3.1.md",
    "apps/local-service/src/provider_runtime.py",
    "apps/local-service/src/openai_protocol_adapter.py",
    "packages/provider-hub/guidance/provider-error-guidance.json",
    "packages/provider-hub/mock-models/models.json",
    "packages/provider-hub/config-forms/openai.json",
    "packages/provider-hub/config-forms/deepseek.json",
    "packages/provider-hub/config-forms/openai-compatible.json",
    "packages/provider-hub/config-forms/custom-base-url.json",
    "packages/provider-hub/config-forms/minimax.json",
    "packages/provider-hub/schemas/provider-config-form.schema.json",
    "packages/provider-hub/schemas/provider-model-list.schema.json",
    "packages/provider-hub/schemas/provider-test-result.schema.json",
    "tests/smoke_provider_hub.py",
    "tests/smoke_provider_api_key_save_button.py",
    "docs/PROVIDER_HUB_FIRST_SLICE_v0.3.2.md",
    "apps/local-service/src/host_runtime.py",
    "packages/host-adapters/src/host-agent-contract.js",
    "packages/host-adapters/schemas/host-registration.schema.json",
    "packages/host-adapters/schemas/host-heartbeat.schema.json",
    "packages/host-adapters/schemas/host-target-lock.schema.json",
    "tests/smoke_host_connection.py",
    "docs/HOST_CONNECTION_FIRST_SLICE_v0.3.3.md",
    "apps/local-service/src/action_runtime.py",
    "apps/local-service/src/command_history.py",
    "tests/smoke_action_execution.py",
    "docs/ACTION_EXECUTION_FIRST_SLICE_v0.3.4.md",
    "apps/desktop/src/local-service-client.js",
    "apps/desktop/src/command-center.js",
    "tests/smoke_desktop_command_center.py",
    "docs/DESKTOP_COMMAND_CENTER_FIRST_SLICE_v0.3.5.md",
    "apps/desktop/prototype/index.html",
    "apps/desktop/prototype/styles.css",
    "apps/desktop/prototype/prototype.js",
    "apps/desktop/prototype/README.md",
    "tests/smoke_desktop_ui_prototype.py",
    "docs/DESKTOP_COMMAND_CENTER_UI_PROTOTYPE_v0.3.6.md",
    "apps/desktop/src/command-center-runtime.js",
    "apps/desktop/src/command-center-fixtures.js",
    "tests/smoke_desktop_runtime_wiring.py",
    "docs/DESKTOP_COMMAND_CENTER_RUNTIME_WIRING_v0.3.7.md",
    "tests/smoke_desktop_runtime_service.py",
    "docs/DESKTOP_COMMAND_CENTER_RUNTIME_SERVICE_SMOKE_v0.3.8.md",
    "tests/smoke_desktop_detail_filter_state.py",
    "docs/DESKTOP_COMMAND_CENTER_DETAIL_FILTER_STATE_v0.3.9.md",
    "tests/smoke_desktop_prototype_detail_ui.py",
    "docs/DESKTOP_COMMAND_CENTER_PROTOTYPE_DETAIL_UI_v0.4.0.md",
    "tests/smoke_desktop_interaction_polish.py",
    "docs/DESKTOP_COMMAND_CENTER_INTERACTION_POLISH_v0.4.1.md",
    "tests/smoke_desktop_runtime_prototype_alignment.py",
    "docs/DESKTOP_COMMAND_CENTER_RUNTIME_PROTOTYPE_ALIGNMENT_v0.4.2.md",
    "tests/smoke_desktop_diagnostics_state.py",
    "docs/DESKTOP_COMMAND_CENTER_DIAGNOSTICS_STATE_v0.4.3.md",
    "tests/smoke_desktop_diagnostics_recovery_ux.py",
    "docs/DESKTOP_COMMAND_CENTER_DIAGNOSTICS_RECOVERY_UX_v0.4.4.md",
    "tests/smoke_desktop_host_readiness_gate.py",
    "docs/DESKTOP_COMMAND_CENTER_HOST_READINESS_GATE_v0.4.5.md",
    "tests/smoke_desktop_readiness_drilldown.py",
    "docs/DESKTOP_COMMAND_CENTER_READINESS_DRILLDOWN_v0.4.6.md",
    "tests/smoke_desktop_host_smoke_handoff.py",
    "docs/DESKTOP_COMMAND_CENTER_HOST_SMOKE_HANDOFF_v0.4.7.md",
    "tests/smoke_desktop_mock_host_smoke_rehearsal.py",
    "docs/DESKTOP_COMMAND_CENTER_MOCK_HOST_SMOKE_REHEARSAL_v0.4.8.md",
    "tests/smoke_desktop_rehearsal_result_panel.py",
    "docs/DESKTOP_COMMAND_CENTER_REHEARSAL_RESULT_PANEL_v0.4.9.md",
    "tests/smoke_desktop_manual_host_smoke_runbook.py",
    "docs/DESKTOP_COMMAND_CENTER_MANUAL_HOST_SMOKE_RUNBOOK_v0.5.0.md",
    "tests/smoke_desktop_runbook_export_feedback_state.py",
    "docs/DESKTOP_COMMAND_CENTER_RUNBOOK_EXPORT_FEEDBACK_STATE_v0.5.1.md",
    "tests/smoke_desktop_manual_host_smoke_evidence_pack.py",
    "docs/DESKTOP_COMMAND_CENTER_MANUAL_HOST_SMOKE_EVIDENCE_PACK_v0.5.2.md",
    "tests/smoke_desktop_manual_host_smoke_review_checklist.py",
    "docs/DESKTOP_COMMAND_CENTER_MANUAL_HOST_SMOKE_REVIEW_CHECKLIST_v0.5.3.md",
    "tests/smoke_desktop_manual_host_smoke_session_draft.py",
    "docs/DESKTOP_COMMAND_CENTER_MANUAL_HOST_SMOKE_SESSION_DRAFT_v0.5.4.md",
    "tests/smoke_desktop_ae_pr_visual_preview.py",
    "docs/DESKTOP_AE_PR_VISUAL_PREVIEW_PASS_v0.5.5.md",
    "tests/smoke_desktop_visual_review_matrix.py",
    "docs/DESKTOP_VISUAL_REVIEW_MATRIX_v0.5.6.md",
    "tests/smoke_desktop_visual_signoff_state.py",
    "docs/DESKTOP_VISUAL_SIGNOFF_STATE_v0.5.7.md",
    "tests/smoke_desktop_visual_evidence_export.py",
    "docs/DESKTOP_VISUAL_EVIDENCE_EXPORT_v0.5.8.md",
    "docs/DESKTOP_VISUAL_EVIDENCE_REVIEW_LOCK_v0.5.9.md",
    "tests/smoke_desktop_visual_evidence_review_lock.py",
]

OLD_PATHS = [
    "packages/shared-core",
    "packages/provider-manager",
    "packages/prompt-engine",
    "packages/storage",
    "packages/shared-ui",
    "docs/user-guide",
    "installers/windows",
    "installers/macos",
]

REQUIRED_TEXT = [
    ("extensions/after-effects/CSXS/manifest.xml", "com.kuroii.motionai.ae"),
    ("extensions/premiere-pro/CSXS/manifest.xml", "com.kuroii.motionai.pr"),
    ("packages/provider-hub/src/provider-errors.js", "检查 API Key"),
    ("packages/provider-hub/src/provider-errors.js", "切换到当前平台可用模型"),
    ("packages/provider-hub/src/provider-errors.js", "等待限流恢复"),
    ("packages/provider-hub/src/provider-errors.js", "检查 Base URL"),
    ("apps/local-service/src/server.py", "X-Kuroii-Session"),
    ("apps/local-service/src/server.py", "PAYLOAD_TOO_LARGE"),
    ("apps/local-service/src/server.py", "CAPABILITY_NOT_FOUND"),
    ("docs/LOCAL_SERVICE_FIRST_SLICE_v0.3.1.md", "/health"),
    ("apps/local-service/src/provider_runtime.py", "MODEL_NOT_FOUND"),
    ("apps/local-service/src/provider_runtime.py", "LIVE_MODEL_DISCOVERY_PROVIDERS = {\"openai\", \"deepseek\", \"openai-compatible\", \"custom-base-url\"}"),
    ("apps/local-service/src/provider_runtime.py", "generate_image as generate_minimax_image"),
    ("apps/local-service/src/minimax_protocol_adapter.py", "MiniMax image generation requires image-01 or image-01-live."),
    ("apps/local-service/src/minimax_protocol_adapter.py", "def generate_music("),
    ("apps/local-service/src/minimax_protocol_adapter.py", "def generate_voice("),
    ("apps/local-service/src/minimax_protocol_adapter.py", "def submit_video("),
    ("apps/local-service/src/minimax_protocol_adapter.py", "def poll_video("),
    ("apps/local-service/src/video_tasks.py", "def save_video_task_artifact("),
    ("apps/local-service/src/asset_library.py", "def list_assets("),
    ("apps/local-service/src/asset_library.py", "def delete_asset("),
    ("apps/local-service/src/server.py", '"/ai/music/generate"'),
    ("apps/local-service/src/server.py", '"/ai/voice/generate"'),
    ("apps/local-service/src/server.py", '"/ai/assets"'),
    ("apps/local-service/src/openai_protocol_adapter.py", "OpenAI-Organization"),
    ("apps/local-service/src/server.py", "/providers/{providerId}/models"),
    ("packages/provider-hub/guidance/provider-error-guidance.json", "检查 Key"),
    ("packages/provider-hub/guidance/provider-error-guidance.json", "切换模型"),
    ("packages/provider-hub/guidance/provider-error-guidance.json", "等待限流"),
    ("packages/provider-hub/guidance/provider-error-guidance.json", "检查 Base URL"),
    ("docs/PROVIDER_HUB_FIRST_SLICE_v0.3.2.md", "Provider Hub First Slice"),
    ("apps/local-service/src/server.py", "/providers/{providerId}/secret"),
    ("apps/local-service/src/server.py", "/provider-profiles/{profileId}/secret"),
    ("apps/local-service/src/server.py", "/provider-profiles/{profileId}"),
    ("apps/local-service/src/provider_profiles.py", "profileInstances"),
    ("apps/desktop/prototype/prototype.js", "providerHubShell"),
    ("tests/smoke_provider_hub_v2.py", "Provider Hub V2 smoke test"),
    ("apps/desktop/prototype/prototype.js", "saveProviderApiKeyButton"),
    ("apps/desktop/prototype/styles.css", ".providerApiKeyRow"),
    ("tests/smoke_provider_api_key_save_button.py", "Provider API key save button smoke test"),
    ("apps/local-service/src/host_runtime.py", "HOST_LOCK_MISMATCH"),
    ("apps/local-service/src/server.py", "/hosts/{host}/heartbeat"),
    ("apps/local-service/src/host_runtime.py", "HOST_OFFLINE"),
    ("extensions/after-effects/client/main.js", "registerHost"),
    ("extensions/premiere-pro/client/main.js", "sendHeartbeat"),
    ("docs/HOST_CONNECTION_FIRST_SLICE_v0.3.3.md", "Host Connection First Slice"),
    ("apps/local-service/src/server.py", "/actions/trusted"),
    ("apps/local-service/src/server.py", "/commands/{commandId}"),
    ("apps/local-service/src/server.py", "TRUSTED_ACTION_EXECUTED"),
    ("apps/local-service/src/server.py", "ACTION_OUT_OF_SCOPE"),
    ("apps/local-service/src/action_runtime.py", "execute_trusted_read_only_action"),
    ("apps/local-service/src/command_history.py", "record_command"),
    ("tests/smoke_action_execution.py", "Action Execution smoke test"),
    ("docs/ACTION_EXECUTION_FIRST_SLICE_v0.3.4.md", "Action Execution First Slice"),
    ("apps/desktop/src/app-shell.js", "commandCenterMode"),
    ("apps/desktop/src/navigation.js", "command-center"),
    ("apps/desktop/src/local-service-client.js", "createLocalServiceClient"),
    ("apps/desktop/src/local-service-client.js", "/hosts/{host}/context"),
    ("apps/desktop/src/command-center.js", "buildCommandCenterViewModel"),
    ("apps/desktop/src/command-center.js", "allowedRiskLevels: [0]"),
    ("packages/i18n/src/locales/zh-CN.json", "命令中心"),
    ("packages/i18n/src/locales/en-US.json", "Command Center"),
    ("tests/smoke_desktop_command_center.py", "Desktop Command Center smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_FIRST_SLICE_v0.3.5.md", "Desktop Command Center First Slice"),
    ("apps/desktop/src/app-shell.js", "prototypePath"),
    ("apps/desktop/prototype/index.html", "hostStrip"),
    ("apps/desktop/prototype/index.html", "languageToggle"),
    ("apps/desktop/prototype/styles.css", "theme-light"),
    ("apps/desktop/prototype/styles.css", "@media (max-width: 840px)"),
    ("apps/desktop/prototype/prototype.js", "refreshFromService"),
    ("apps/desktop/prototype/prototype.js", "PROTOTYPE_MOCK_EXECUTED"),
    ("tests/smoke_desktop_ui_prototype.py", "Desktop UI prototype smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_UI_PROTOTYPE_v0.3.6.md", "Desktop Command Center UI Prototype"),
    ("apps/desktop/src/app-shell.js", "runtimeModule"),
    ("apps/desktop/src/command-center-runtime.js", "createCommandCenterRuntime"),
    ("apps/desktop/src/command-center-runtime.js", "runReadOnlyAction"),
    ("apps/desktop/src/command-center-runtime.js", "RUNTIME_MOCK_EXECUTED"),
    ("apps/desktop/src/command-center-fixtures.js", "commandCenterMockData"),
    ("apps/desktop/prototype/prototype.js", "runtimeWiring"),
    ("tests/smoke_desktop_runtime_wiring.py", "Desktop runtime wiring smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_RUNTIME_WIRING_v0.3.7.md", "Desktop Command Center Runtime Wiring"),
    ("apps/desktop/src/app-shell.js", "runtimeServiceSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterRuntimeServiceSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "serviceBackedMethods"),
    ("tests/smoke_desktop_runtime_service.py", "Desktop runtime service smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_RUNTIME_SERVICE_SMOKE_v0.3.8.md", "Desktop Command Center Runtime Smoke With Service"),
    ("apps/desktop/src/app-shell.js", "detailFilterStateSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterDefaultHistoryFilters"),
    ("apps/desktop/src/command-center.js", "buildCommandDetail"),
    ("apps/desktop/src/command-center.js", "buildRecoveryState"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterDetailFilterRuntime"),
    ("apps/desktop/src/command-center-runtime.js", "openCommandDetail"),
    ("apps/desktop/src/command-center-runtime.js", "recoverFromError"),
    ("packages/i18n/src/locales/zh-CN.json", "正在执行只读动作"),
    ("packages/i18n/src/locales/en-US.json", "Retry refresh"),
    ("tests/smoke_desktop_detail_filter_state.py", "Desktop detail/filter state smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_DETAIL_FILTER_STATE_v0.3.9.md", "Desktop Command Center Detail and Filter State"),
    ("apps/desktop/src/app-shell.js", "prototypeDetailUiSmoke"),
    ("apps/desktop/prototype/index.html", "historyFilters"),
    ("apps/desktop/prototype/index.html", "recoveryPanel"),
    ("apps/desktop/prototype/styles.css", ".filterBar"),
    ("apps/desktop/prototype/prototype.js", "detailFilterUi"),
    ("apps/desktop/prototype/prototype.js", "historyServiceQuery"),
    ("apps/desktop/prototype/README.md", "Result History Filters"),
    ("tests/smoke_desktop_prototype_detail_ui.py", "Desktop prototype detail UI smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_PROTOTYPE_DETAIL_UI_v0.4.0.md", "Desktop Command Center Prototype Detail UI"),
    ("apps/desktop/src/app-shell.js", "interactionPolishSmoke"),
    ("apps/desktop/prototype/index.html", "skipLink"),
    ("apps/desktop/prototype/index.html", "detailSummary"),
    ("apps/desktop/prototype/styles.css", ".emptyState"),
    ("apps/desktop/prototype/prototype.js", "interactionPolish"),
    ("apps/desktop/prototype/prototype.js", "applyFocusAfterRender"),
    ("tests/smoke_desktop_interaction_polish.py", "Desktop interaction polish smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_INTERACTION_POLISH_v0.4.1.md", "Desktop Command Center Interaction Polish"),
    ("apps/desktop/src/app-shell.js", "runtimePrototypeAlignmentSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterRuntimePrototypeAlignment"),
    ("apps/desktop/src/command-center.js", "commandCenterSharedEmptyStates"),
    ("apps/desktop/src/command-center.js", "buildCommandCenterEmptyStates"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterRuntimePrototypeAlignmentSmoke"),
    ("apps/desktop/prototype/index.html", "data-recovery-action=\"retry-refresh\""),
    ("apps/desktop/prototype/prototype.js", "runtimePrototypeAlignment"),
    ("apps/desktop/prototype/prototype.js", "prototypeStateMap"),
    ("apps/desktop/prototype/prototype.js", "normalizePrototypeServiceError"),
    ("apps/desktop/prototype/prototype.js", "emptyStateMarkup"),
    ("tests/smoke_desktop_runtime_prototype_alignment.py", "Desktop runtime/prototype alignment smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_RUNTIME_PROTOTYPE_ALIGNMENT_v0.4.2.md", "Desktop Command Center Runtime-Prototype Alignment"),
    ("apps/desktop/src/app-shell.js", "diagnosticsStateSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterDiagnosticsFirstSlice"),
    ("apps/desktop/src/command-center.js", "buildCommandCenterDiagnostics"),
    ("apps/desktop/src/command-center.js", "HOST_HEARTBEAT_STALE"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterDiagnosticsStateSmoke"),
    ("apps/desktop/prototype/index.html", "diagnosticsPanel"),
    ("apps/desktop/prototype/styles.css", ".diagnosticItem"),
    ("apps/desktop/prototype/prototype.js", "diagnosticsState"),
    ("apps/desktop/prototype/prototype.js", "buildPrototypeDiagnostics"),
    ("tests/smoke_desktop_diagnostics_state.py", "Desktop diagnostics state smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_DIAGNOSTICS_STATE_v0.4.3.md", "Desktop Command Center Diagnostics State"),
    ("apps/desktop/src/app-shell.js", "diagnosticsRecoveryUxSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterDiagnosticsRecoveryUx"),
    ("apps/desktop/src/command-center.js", "resolveDiagnosticRecoveryActions"),
    ("apps/desktop/src/command-center.js", "view-latest-error"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterDiagnosticsRecoveryUxSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "recoverDiagnostic"),
    ("apps/desktop/prototype/styles.css", ".diagnosticAction"),
    ("apps/desktop/prototype/prototype.js", "diagnosticsRecoveryUx"),
    ("apps/desktop/prototype/prototype.js", "handleDiagnosticRecovery"),
    ("apps/desktop/prototype/prototype.js", "data-diagnostic-action"),
    ("packages/i18n/src/locales/zh-CN.json", "查看最近错误"),
    ("packages/i18n/src/locales/en-US.json", "View latest error"),
    ("tests/smoke_desktop_diagnostics_recovery_ux.py", "Desktop diagnostics recovery UX smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_DIAGNOSTICS_RECOVERY_UX_v0.4.4.md", "Desktop Command Center Diagnostics Recovery UX"),
    ("apps/desktop/src/app-shell.js", "hostReadinessGateSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterHostReadinessGate"),
    ("apps/desktop/src/command-center.js", "buildHostReadinessGate"),
    ("apps/desktop/src/command-center.js", "canEnterHostTest"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterHostReadinessGateSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "hostReadinessContract"),
    ("apps/desktop/prototype/index.html", "hostReadinessPanel"),
    ("apps/desktop/prototype/styles.css", ".readinessItem"),
    ("apps/desktop/prototype/prototype.js", "hostReadinessGate"),
    ("apps/desktop/prototype/prototype.js", "buildPrototypeHostReadinessGate"),
    ("apps/desktop/prototype/prototype.js", "data-readiness-status"),
    ("packages/i18n/src/locales/zh-CN.json", "宿主预检"),
    ("packages/i18n/src/locales/en-US.json", "Host Readiness"),
    ("tests/smoke_desktop_host_readiness_gate.py", "Desktop host readiness gate smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_HOST_READINESS_GATE_v0.4.5.md", "Desktop Command Center Host Readiness Gate"),
    ("apps/desktop/src/app-shell.js", "readinessDrilldownSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterReadinessDrilldown"),
    ("apps/desktop/src/command-center.js", "resolveReadinessDrilldownTarget"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterReadinessDrilldownSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "readinessDrilldownContract"),
    ("apps/desktop/prototype/index.html", "id=\"actionList\" aria-live=\"polite\" tabindex=\"-1\""),
    ("apps/desktop/prototype/prototype.js", "readinessDrilldown"),
    ("apps/desktop/prototype/prototype.js", "handleReadinessDrilldown"),
    ("apps/desktop/prototype/prototype.js", "data-readiness-drilldown"),
    ("apps/desktop/prototype/prototype.js", "data-readiness-target"),
    ("apps/desktop/prototype/styles.css", ".readinessAction"),
    ("packages/i18n/src/locales/zh-CN.json", "查看对应区域"),
    ("packages/i18n/src/locales/en-US.json", "View related area"),
    ("tests/smoke_desktop_readiness_drilldown.py", "Desktop readiness drilldown smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_READINESS_DRILLDOWN_v0.4.6.md", "Desktop Command Center Readiness Drilldown"),
    ("apps/desktop/src/app-shell.js", "hostSmokeHandoffSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterHostSmokeHandoffChecklist"),
    ("apps/desktop/src/command-center.js", "automaticHostLaunchAllowed: false"),
    ("apps/desktop/src/command-center.js", "forbiddenActionPatterns"),
    ("apps/desktop/src/command-center.js", "allowedReadOnlyActions"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterHostSmokeHandoffSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "hostSmokeHandoffChecklist"),
    ("apps/desktop/prototype/prototype.js", "hostSmokeHandoff"),
    ("tests/smoke_desktop_host_smoke_handoff.py", "Desktop host smoke handoff smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_HOST_SMOKE_HANDOFF_v0.4.7.md", "Desktop Command Center Host Smoke Handoff Checklist"),
    ("apps/desktop/src/app-shell.js", "mockHostSmokeRehearsalSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterMockHostSmokeRehearsal"),
    ("apps/desktop/src/command-center.js", "buildMockHostSmokeRehearsal"),
    ("apps/desktop/src/command-center.js", "simulatedResultHistory"),
    ("apps/desktop/src/command-center.js", "failure-interrupts-run"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterMockHostSmokeRehearsalSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "previewMockHostSmokeRehearsal"),
    ("apps/desktop/prototype/prototype.js", "mockHostSmokeRehearsal"),
    ("tests/smoke_desktop_mock_host_smoke_rehearsal.py", "Desktop mock host smoke rehearsal smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_MOCK_HOST_SMOKE_REHEARSAL_v0.4.8.md", "Desktop Command Center Mock Host Smoke Rehearsal Runner"),
    ("apps/desktop/src/app-shell.js", "rehearsalResultPanelSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterRehearsalResultPanel"),
    ("apps/desktop/src/command-center.js", "buildRehearsalResultPanelState"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterRehearsalResultPanelSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "previewRehearsalResultPanel"),
    ("apps/desktop/prototype/index.html", "rehearsalResultPanel"),
    ("apps/desktop/prototype/prototype.js", "rehearsalResultPanel"),
    ("apps/desktop/prototype/prototype.js", "renderRehearsalResultPanel"),
    ("apps/desktop/prototype/styles.css", ".rehearsalPanel"),
    ("packages/i18n/src/locales/zh-CN.json", "彩排结果"),
    ("packages/i18n/src/locales/en-US.json", "Rehearsal Result"),
    ("tests/smoke_desktop_rehearsal_result_panel.py", "Desktop rehearsal result panel smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_REHEARSAL_RESULT_PANEL_v0.4.9.md", "Desktop Command Center Rehearsal Result Panel"),
    ("apps/desktop/src/app-shell.js", "manualHostSmokeRunbookSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterManualHostSmokeRunbook"),
    ("apps/desktop/src/command-center.js", "buildManualHostSmokeRunbook"),
    ("apps/desktop/src/command-center.js", "copy-export-read-only-runbook"),
    ("apps/desktop/src/command-center.js", "outputFormats: [\"markdown\", \"json\"]"),
    ("apps/desktop/src/command-center.js", "automaticHostLaunchAllowed: false"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterManualHostSmokeRunbookSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "manualHostSmokeRunbookContract"),
    ("apps/desktop/src/command-center-runtime.js", "previewManualHostSmokeRunbook"),
    ("apps/desktop/prototype/index.html", "manualHostSmokeRunbookPanel"),
    ("apps/desktop/prototype/index.html", "data-host-smoke-runbook"),
    ("apps/desktop/prototype/index.html", "data-runbook-copy"),
    ("apps/desktop/prototype/index.html", "data-runbook-export=\"markdown\""),
    ("apps/desktop/prototype/index.html", "data-runbook-export=\"json\""),
    ("apps/desktop/prototype/index.html", "data-runbook-preview"),
    ("apps/desktop/prototype/prototype.js", "buildPrototypeManualHostSmokeRunbook"),
    ("apps/desktop/prototype/prototype.js", "renderManualHostSmokeRunbook"),
    ("apps/desktop/prototype/prototype.js", "copyManualHostSmokeRunbook"),
    ("apps/desktop/prototype/prototype.js", "exportManualHostSmokeRunbook"),
    ("apps/desktop/prototype/styles.css", ".runbookPanel"),
    ("packages/i18n/src/locales/zh-CN.json", "宿主 Smoke Runbook"),
    ("packages/i18n/src/locales/en-US.json", "Host Smoke Runbook"),
    ("tests/smoke_desktop_manual_host_smoke_runbook.py", "Desktop manual host smoke runbook smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_MANUAL_HOST_SMOKE_RUNBOOK_v0.5.0.md", "Desktop Command Center Manual Host Smoke Runbook"),
    ("apps/desktop/src/app-shell.js", "runbookExportFeedbackStateSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterRunbookExportFeedbackState"),
    ("apps/desktop/src/command-center.js", "buildRunbookExportFeedbackState"),
    ("apps/desktop/src/command-center.js", "inline-feedback-and-persisted-state"),
    ("apps/desktop/src/command-center.js", "kuroii.motionai.commandCenter.runbookExportState.v1"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterRunbookExportFeedbackStateSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "runbookExportFeedbackContract"),
    ("apps/desktop/src/command-center-runtime.js", "recordRunbookExportFeedback"),
    ("apps/desktop/prototype/index.html", "runbookFeedback"),
    ("apps/desktop/prototype/index.html", "data-runbook-feedback"),
    ("apps/desktop/prototype/index.html", "data-runbook-persisted-state"),
    ("apps/desktop/prototype/prototype.js", "runbookExportFeedbackStorageKey"),
    ("apps/desktop/prototype/prototype.js", "readPersistedRunbookFeedbackState"),
    ("apps/desktop/prototype/prototype.js", "writePersistedRunbookFeedbackState"),
    ("apps/desktop/prototype/prototype.js", "buildPrototypeRunbookExportFeedbackState"),
    ("apps/desktop/prototype/prototype.js", "saveRunbookExportFeedbackState"),
    ("apps/desktop/prototype/prototype.js", "renderRunbookFeedback"),
    ("apps/desktop/prototype/styles.css", ".runbookFeedback"),
    ("packages/i18n/src/locales/zh-CN.json", "Markdown 已复制到剪贴板"),
    ("packages/i18n/src/locales/en-US.json", "Markdown copied to clipboard"),
    ("tests/smoke_desktop_runbook_export_feedback_state.py", "Desktop runbook export feedback state smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_RUNBOOK_EXPORT_FEEDBACK_STATE_v0.5.1.md", "Desktop Command Center Runbook Export Feedback State"),
    ("apps/desktop/src/app-shell.js", "manualHostSmokeEvidencePackSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterManualHostSmokeEvidencePack"),
    ("apps/desktop/src/command-center.js", "buildManualHostSmokeEvidencePack"),
    ("apps/desktop/src/command-center.js", "local-read-only-evidence-pack"),
    ("apps/desktop/src/command-center.js", "data-evidence-notes"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterManualHostSmokeEvidencePackSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "manualHostSmokeEvidencePackContract"),
    ("apps/desktop/src/command-center-runtime.js", "previewManualHostSmokeEvidencePack"),
    ("apps/desktop/prototype/index.html", "manualHostSmokeEvidencePackPanel"),
    ("apps/desktop/prototype/index.html", "data-host-smoke-evidence-pack"),
    ("apps/desktop/prototype/index.html", "data-evidence-pack-copy"),
    ("apps/desktop/prototype/index.html", "data-evidence-pack-export=\"markdown\""),
    ("apps/desktop/prototype/index.html", "data-evidence-pack-export=\"json\""),
    ("apps/desktop/prototype/index.html", "data-evidence-notes"),
    ("apps/desktop/prototype/prototype.js", "evidencePackNotesStorageKey"),
    ("apps/desktop/prototype/prototype.js", "buildPrototypeManualHostSmokeEvidencePack"),
    ("apps/desktop/prototype/prototype.js", "renderManualHostSmokeEvidencePack"),
    ("apps/desktop/prototype/prototype.js", "copyManualHostSmokeEvidencePack"),
    ("apps/desktop/prototype/prototype.js", "exportManualHostSmokeEvidencePack"),
    ("apps/desktop/prototype/styles.css", ".evidencePackPanel"),
    ("packages/i18n/src/locales/zh-CN.json", "宿主 Smoke 证据包"),
    ("packages/i18n/src/locales/en-US.json", "Host Smoke Evidence Pack"),
    ("tests/smoke_desktop_manual_host_smoke_evidence_pack.py", "Desktop manual host smoke evidence pack smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_MANUAL_HOST_SMOKE_EVIDENCE_PACK_v0.5.2.md", "Desktop Command Center Manual Host Smoke Evidence Pack"),
    ("apps/desktop/src/app-shell.js", "manualHostSmokeReviewChecklistSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterManualHostSmokeReviewChecklist"),
    ("apps/desktop/src/command-center.js", "buildManualHostSmokeReviewChecklist"),
    ("apps/desktop/src/command-center.js", "manual-host-smoke-review-checklist"),
    ("apps/desktop/src/command-center.js", "kuroii.motionai.commandCenter.reviewChecklistState.v1"),
    ("apps/desktop/src/command-center.js", "data-review-checklist-toggle"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterManualHostSmokeReviewChecklistSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "manualHostSmokeReviewChecklistContract"),
    ("apps/desktop/src/command-center-runtime.js", "previewManualHostSmokeReviewChecklist"),
    ("apps/desktop/src/command-center-runtime.js", "updateReviewChecklistState"),
    ("apps/desktop/prototype/index.html", "manualHostSmokeReviewChecklistPanel"),
    ("apps/desktop/prototype/index.html", "data-host-smoke-review-checklist"),
    ("apps/desktop/prototype/index.html", "data-review-checklist-reset"),
    ("apps/desktop/prototype/prototype.js", "reviewChecklistStorageKey"),
    ("apps/desktop/prototype/prototype.js", "buildPrototypeManualHostSmokeReviewChecklist"),
    ("apps/desktop/prototype/prototype.js", "renderManualHostSmokeReviewChecklist"),
    ("apps/desktop/prototype/prototype.js", "resetReviewChecklist"),
    ("apps/desktop/prototype/styles.css", ".reviewChecklistPanel"),
    ("apps/desktop/prototype/styles.css", ".reviewChecklistItem"),
    ("packages/i18n/src/locales/zh-CN.json", "宿主 Smoke 复核清单"),
    ("packages/i18n/src/locales/en-US.json", "Host Smoke Review Checklist"),
    ("tests/smoke_desktop_manual_host_smoke_review_checklist.py", "Desktop manual host smoke review checklist smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_MANUAL_HOST_SMOKE_REVIEW_CHECKLIST_v0.5.3.md", "Desktop Command Center Manual Host Smoke Review Checklist"),
    ("apps/desktop/src/app-shell.js", "manualHostSmokeSessionDraftSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterManualHostSmokeSessionDraft"),
    ("apps/desktop/src/command-center.js", "buildManualHostSmokeSessionDraft"),
    ("apps/desktop/src/command-center.js", "manual-host-smoke-session-draft"),
    ("apps/desktop/src/command-center.js", "kuroii.motionai.commandCenter.hostSmokeSessionDraft.v1"),
    ("apps/desktop/src/command-center.js", "data-session-draft-save"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterManualHostSmokeSessionDraftSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "manualHostSmokeSessionDraftContract"),
    ("apps/desktop/src/command-center-runtime.js", "previewManualHostSmokeSessionDraft"),
    ("apps/desktop/src/command-center-runtime.js", "updateManualHostSmokeSessionDraftState"),
    ("apps/desktop/prototype/index.html", "manualHostSmokeSessionDraftPanel"),
    ("apps/desktop/prototype/index.html", "data-host-smoke-session-draft"),
    ("apps/desktop/prototype/index.html", "data-session-draft-save"),
    ("apps/desktop/prototype/index.html", "data-session-draft-export=\"json\""),
    ("apps/desktop/prototype/prototype.js", "sessionDraftStorageKey"),
    ("apps/desktop/prototype/prototype.js", "buildPrototypeManualHostSmokeSessionDraft"),
    ("apps/desktop/prototype/prototype.js", "renderManualHostSmokeSessionDraft"),
    ("apps/desktop/prototype/prototype.js", "resetManualHostSmokeSessionDraft"),
    ("apps/desktop/prototype/styles.css", ".sessionDraftPanel"),
    ("apps/desktop/prototype/styles.css", ".sessionDraftPreview"),
    ("packages/i18n/src/locales/zh-CN.json", "宿主 Smoke Session 草案"),
    ("packages/i18n/src/locales/en-US.json", "Host Smoke Session Draft"),
    ("tests/smoke_desktop_manual_host_smoke_session_draft.py", "Desktop manual host smoke session draft smoke test"),
    ("docs/DESKTOP_COMMAND_CENTER_MANUAL_HOST_SMOKE_SESSION_DRAFT_v0.5.4.md", "Desktop Command Center Manual Host Smoke Session Draft"),
    ("apps/desktop/src/app-shell.js", "visualPreviewPassSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterVisualPreviewPass"),
    ("apps/desktop/src/command-center.js", "buildCommandCenterVisualPreview"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterVisualPreviewPassSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "previewVisualPreviewPass"),
    ("apps/desktop/prototype/index.html", "visualPreviewPanel"),
    ("apps/desktop/prototype/index.html", "data-visual-preview-pass"),
    ("apps/desktop/prototype/prototype.js", "renderVisualPreviewPass"),
    ("apps/desktop/prototype/styles.css", ".visualPreviewPanel"),
    ("extensions/after-effects/client/index.html", "data-visual-preview-panel"),
    ("extensions/after-effects/client/main.js", "AE Compact"),
    ("extensions/after-effects/client/styles.css", ".modeRail"),
    ("extensions/premiere-pro/client/index.html", "data-visual-preview-panel"),
    ("extensions/premiere-pro/client/main.js", "PR Compact"),
    ("extensions/premiere-pro/client/styles.css", ".modeRail"),
    ("packages/i18n/src/locales/zh-CN.json", "三端视觉预览"),
    ("packages/i18n/src/locales/en-US.json", "Visual Preview"),
    ("tests/smoke_desktop_ae_pr_visual_preview.py", "Desktop / AE / PR visual preview pass smoke test"),
    ("docs/DESKTOP_AE_PR_VISUAL_PREVIEW_PASS_v0.5.5.md", "Desktop / AE / PR Visual Preview Pass"),
    ("apps/desktop/src/app-shell.js", "visualReviewMatrixSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterVisualReviewMatrix"),
    ("apps/desktop/src/command-center.js", "buildCommandCenterVisualReviewMatrix"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterVisualReviewMatrixSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "previewVisualReviewMatrix"),
    ("apps/desktop/prototype/index.html", "visualReviewMatrixPanel"),
    ("apps/desktop/prototype/index.html", "data-visual-review-matrix"),
    ("apps/desktop/prototype/prototype.js", "renderVisualReviewMatrix"),
    ("apps/desktop/prototype/styles.css", ".visualReviewPanel"),
    ("packages/i18n/src/locales/zh-CN.json", "视觉评审矩阵"),
    ("packages/i18n/src/locales/en-US.json", "Visual Review Matrix"),
    ("tests/smoke_desktop_visual_review_matrix.py", "Desktop visual review matrix smoke test"),
    ("docs/DESKTOP_VISUAL_REVIEW_MATRIX_v0.5.6.md", "Desktop Visual Review Matrix and Screenshot Checklist"),
    ("apps/desktop/src/app-shell.js", "visualSignoffStateSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterVisualSignoffState"),
    ("apps/desktop/src/command-center.js", "buildCommandCenterVisualSignoffState"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterVisualSignoffStateSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "previewVisualSignoffState"),
    ("apps/desktop/src/command-center-runtime.js", "updateVisualSignoffState"),
    ("apps/desktop/prototype/index.html", "visualSignoffPanel"),
    ("apps/desktop/prototype/index.html", "data-visual-signoff-state"),
    ("apps/desktop/prototype/prototype.js", "renderVisualSignoffState"),
    ("apps/desktop/prototype/prototype.js", "visualSignoffStorageKey"),
    ("apps/desktop/prototype/styles.css", ".visualSignoffPanel"),
    ("packages/i18n/src/locales/zh-CN.json", "视觉签核"),
    ("packages/i18n/src/locales/en-US.json", "Visual Sign-off"),
    ("tests/smoke_desktop_visual_signoff_state.py", "Desktop visual sign-off state smoke test"),
    ("docs/DESKTOP_VISUAL_SIGNOFF_STATE_v0.5.7.md", "Desktop Manual Visual Sign-off State and Findings Backlog"),
    ("apps/desktop/src/app-shell.js", "visualEvidenceExportSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterVisualEvidenceExport"),
    ("apps/desktop/src/command-center.js", "buildCommandCenterVisualEvidenceExport"),
    ("apps/desktop/src/command-center.js", "pre-host-visual-evidence-export"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterVisualEvidenceExportSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "previewVisualEvidenceExport"),
    ("apps/desktop/prototype/index.html", "visualEvidenceExportPanel"),
    ("apps/desktop/prototype/index.html", "data-visual-evidence-export"),
    ("apps/desktop/prototype/prototype.js", "buildPrototypeVisualEvidenceExport"),
    ("apps/desktop/prototype/prototype.js", "copyVisualEvidenceExport"),
    ("apps/desktop/prototype/prototype.js", "exportVisualEvidenceExport"),
    ("apps/desktop/prototype/styles.css", ".visualEvidencePanel"),
    ("packages/i18n/src/locales/zh-CN.json", "视觉证据导出"),
    ("packages/i18n/src/locales/en-US.json", "Visual Evidence Export"),
    ("tests/smoke_desktop_visual_evidence_export.py", "Desktop visual evidence export smoke test"),
    ("docs/DESKTOP_VISUAL_EVIDENCE_EXPORT_v0.5.8.md", "Desktop Pre-host Visual Evidence Export"),
    ("apps/desktop/src/app-shell.js", "visualEvidenceReviewLockSmoke"),
    ("apps/desktop/src/command-center.js", "commandCenterVisualEvidenceReviewLock"),
    ("apps/desktop/src/command-center.js", "buildCommandCenterVisualEvidenceReviewLock"),
    ("apps/desktop/src/command-center-runtime.js", "commandCenterVisualEvidenceReviewLockSmoke"),
    ("apps/desktop/src/command-center-runtime.js", "previewVisualEvidenceReviewLock"),
    ("apps/desktop/prototype/index.html", "visualEvidenceReviewLockPanel"),
    ("apps/desktop/prototype/index.html", "data-visual-evidence-review-lock"),
    ("apps/desktop/prototype/prototype.js", "renderVisualEvidenceReviewLock"),
    ("apps/desktop/prototype/prototype.js", "visualEvidenceReviewLockStorageKey"),
    ("apps/desktop/prototype/styles.css", ".visualEvidenceReviewLockPanel"),
    ("packages/i18n/src/locales/zh-CN.json", "视觉证据复核锁定"),
    ("packages/i18n/src/locales/en-US.json", "Evidence Review Lock"),
    ("tests/smoke_desktop_visual_evidence_review_lock.py", "Desktop visual evidence review lock smoke test"),
    ("docs/DESKTOP_VISUAL_EVIDENCE_REVIEW_LOCK_v0.5.9.md", "Desktop Pre-host Visual Evidence Review Lock"),
]


def fail(message):
    print(f"[FAIL] {message}")
    return 1


def main():
    failures = []
    for rel in REQUIRED_PATHS:
        if not (ROOT / rel).exists():
            failures.append(f"missing required path: {rel}")
    for rel in OLD_PATHS:
        if (ROOT / rel).exists():
            failures.append(f"old v0.2.4 path still exists: {rel}")
    for rel, needle in REQUIRED_TEXT:
        text = (ROOT / rel).read_text(encoding="utf-8")
        if needle not in text:
            failures.append(f"missing text '{needle}' in {rel}")
    for json_file in ROOT.rglob("*.json"):
        try:
            json.loads(json_file.read_text(encoding="utf-8"))
        except Exception as exc:
            failures.append(f"invalid json: {json_file.relative_to(ROOT)}: {exc}")
    if failures:
        for item in failures:
            print(f"[FAIL] {item}")
        return 1
    print("[OK] Kuroii Motion AI Suite v3.0 structure validation passed")
    print(f"[OK] checked {len(REQUIRED_PATHS)} required paths")
    return 0

if __name__ == "__main__":
    sys.exit(main())
