export const desktopShell = {
  appId: "com.kuroii.motionai.desktop",
  version: "0.5.9-alpha.0",
  workspaces: ["general", "after-effects", "premiere-pro", "cross-host"],
  serviceDependency: "@kuroii/local-service",
  localService: {
    baseUrl: "http://127.0.0.1:17631",
    sessionHeader: "X-Kuroii-Session",
    requiredRoutes: ["/hosts", "/hosts/{host}/context", "/actions/trusted", "/commands"],
    commandCenterMode: "read-only-first",
    prototypePath: "apps/desktop/prototype/index.html",
    runtimeModule: "apps/desktop/src/command-center-runtime.js",
    fixtureModule: "apps/desktop/src/command-center-fixtures.js",
    runtimeServiceSmoke: "tests/smoke_desktop_runtime_service.py",
    detailFilterStateSmoke: "tests/smoke_desktop_detail_filter_state.py",
    prototypeDetailUiSmoke: "tests/smoke_desktop_prototype_detail_ui.py",
    interactionPolishSmoke: "tests/smoke_desktop_interaction_polish.py",
    themeContrastSmoke: "tests/smoke_theme_contrast.py",
    runtimePrototypeAlignmentSmoke: "tests/smoke_desktop_runtime_prototype_alignment.py",
    diagnosticsStateSmoke: "tests/smoke_desktop_diagnostics_state.py",
    diagnosticsRecoveryUxSmoke: "tests/smoke_desktop_diagnostics_recovery_ux.py",
    hostReadinessGateSmoke: "tests/smoke_desktop_host_readiness_gate.py",
    readinessDrilldownSmoke: "tests/smoke_desktop_readiness_drilldown.py",
    hostSmokeHandoffSmoke: "tests/smoke_desktop_host_smoke_handoff.py",
    mockHostSmokeRehearsalSmoke: "tests/smoke_desktop_mock_host_smoke_rehearsal.py",
    rehearsalResultPanelSmoke: "tests/smoke_desktop_rehearsal_result_panel.py",
    manualHostSmokeRunbookSmoke: "tests/smoke_desktop_manual_host_smoke_runbook.py",
    runbookExportFeedbackStateSmoke: "tests/smoke_desktop_runbook_export_feedback_state.py",
    manualHostSmokeEvidencePackSmoke: "tests/smoke_desktop_manual_host_smoke_evidence_pack.py",
    manualHostSmokeReviewChecklistSmoke: "tests/smoke_desktop_manual_host_smoke_review_checklist.py",
    manualHostSmokeSessionDraftSmoke: "tests/smoke_desktop_manual_host_smoke_session_draft.py",
    visualPreviewPassSmoke: "tests/smoke_desktop_ae_pr_visual_preview.py",
    visualReviewMatrixSmoke: "tests/smoke_desktop_visual_review_matrix.py",
    visualSignoffStateSmoke: "tests/smoke_desktop_visual_signoff_state.py",
    visualEvidenceExportSmoke: "tests/smoke_desktop_visual_evidence_export.py",
    visualEvidenceReviewLockSmoke: "tests/smoke_desktop_visual_evidence_review_lock.py",
  },
  settings: {
    theme: "system",
    locale: "zh-CN",
    density: "comfortable",
    sidebar: "expanded"
  }
};
